root: true
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier
rules:
  no-console: off
  react/react-in-jsx-scope: off
  '@typescript-eslint/no-unused-vars': [warn, { ignoreRestSiblings: true, varsIgnorePattern: '^_$' }]
  '@typescript-eslint/no-explicit-any': off 
  '@typescript-eslint/no-unsafe-member-access': off 
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-call': off 
  '@typescript-eslint/no-unsafe-argument': off 
  '@typescript-eslint/no-floating-promises': off 
  '@typescript-eslint/await-thenable': off 
  '@typescript-eslint/restrict-template-expressions': off 
  '@typescript-eslint/no-unsafe-return': off 
